[build]
  base    = "site"
  publish = "public"
  command = "npm run build"
  # Always build the site, regardless of code updates: https://bit.ly/3fxbQO6
  ignore = "sh this-always-fails"

[[plugins]]
  package = "netlify-plugin-algolia-export"
